-- AlterTable
ALTER TABLE "cars" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "region_id" DROP NOT NULL,
ALTER COLUMN "category_id" DROP NOT NULL,
ALTER COLUMN "model_name" DROP NOT NULL,
ALTER COLUMN "model_year" DROP NOT NULL,
ALTER COLUMN "body_type_id" DROP NOT NULL,
ALTER COLUMN "running" DROP NOT NULL,
ALTER COLUMN "mission_id" DROP NOT NULL,
ALTER COLUMN "drive_system" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "color" DROP NOT NULL,
ALTER COLUMN "length" DROP NOT NULL,
ALTER COLUMN "width" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "remaining_car_inspection" DROP NOT NULL,
ALTER COLUMN "repair_history" DROP NOT NULL,
ALTER COLUMN "fuel" DROP NOT NULL,
ALTER COLUMN "handle" DROP NOT NULL,
ALTER COLUMN "passenger" DROP NOT NULL,
ALTER COLUMN "number_doors" DROP NOT NULL,
ALTER COLUMN "displacement" DROP NOT NULL,
ALTER COLUMN "slide_door" DROP NOT NULL,
ALTER COLUMN "total_payment" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "has_certified" DROP NOT NULL,
ALTER COLUMN "guaranteed" DROP NOT NULL,
ALTER COLUMN "load_display" DROP NOT NULL,
ALTER COLUMN "comment_person" DROP NOT NULL;

-- CreateTable
CREATE TABLE "color" (
    "id" INTEGER NOT NULL,
    "class" TEXT NOT NULL,

    CONSTRAINT "color_pkey" PRIMARY KEY ("id")
);
